name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-type:
        description: Deploy Type (preview, uat, prod)
        required: true
        default: 'preview'
      git-ref:
        description: Git Ref (Optional)
        required: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Latest)
        if: github.event.inputs.git-ref == ''
        uses: actions/checkout@v2
      - name: Checkout (Custom Ref)
        if: github.event.inputs.git-ref != ''
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Build Artifacts - public/
        uses: actions/upload-artifact@v2
        with:
          name: public-14.x
          path: ${{ github.workspace }}/public/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Latest)
        if: github.event.inputs.git-ref == ''
        uses: actions/checkout@v2
      - name: Checkout (Custom Ref)
        if: github.event.inputs.git-ref != ''
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Create Artifact Directories
        run: |
          mkdir -p ${{ github.workspace }}/public
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: public-14.x
          path: ${{ github.workspace }}/public
      - name: Deploy PREVIEW
        if: github.event.inputs.deploy-type == 'preview'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if [[ -n ${NETLIFY_SITE_ID} && -n ${NETLIFY_AUTH_TOKEN} ]] ; then
            npm run deploy:preview
          fi
      - name: Deploy UAT
        if: github.event.inputs.deploy-type == 'uat'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if [[ -n ${NETLIFY_SITE_ID} && -n ${NETLIFY_AUTH_TOKEN} ]] ; then
            npm run deploy:uat
          fi
      - name: Deploy PROD
        if: github.event.inputs.deploy-type == 'prod'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if [[ -n ${NETLIFY_SITE_ID} && -n ${NETLIFY_AUTH_TOKEN} ]] ; then
            npm run deploy:prod
          fi
