name: Pull Request

on:
  pull_request:
    branches: [master]
    types: [opened, edited, reopened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and Test
    environment: pr_build_environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout (Latest)
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Upload Test Artifacts - coverage/
        if: github.event.inputs.upload-artifacts == 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.node-version }}
          path: ${{ github.workspace }}/coverage/
          retention-days: 1
      - name: Upload Test Coverage - Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: npm run build
      - name: Test E2E
        run: npm run test:e2e:docker
      - name: Upload Test E2E Artifacts - cypress/videos/
        if: github.event.inputs.upload-artifacts == 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos-${{ matrix.node-version }}
          path: ${{ github.workspace }}/cypress/videos/
          retention-days: 1
      - name: Upload Test E2E Artifacts - cypress/screenshots/
        if: github.event.inputs.upload-artifacts == 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots-${{ matrix.node-version }}
          path: ${{ github.workspace }}/cypress/screenshots/
          retention-days: 1
      - name: Test Visual
        run: npm run test:visual:docker
      - name: Compress Test Visual Artifacts
        if: ${{ always() }}
        run: |
          find . -name '__diff_output__' | tar -cvjf tests-visual-job-artifacts.tar.bz2 --files-from -
      - name: Upload Test Visual Artifacts - tests-visual-job-artifacts.tar.bz2
        if: github.event.inputs.upload-artifacts == 'yes'
        uses: actions/upload-artifact@v2
        with:
          name: tests-visual-job-artifacts-${{ matrix.node-version }}.tar.bz2
          path: ${{ github.workspace }}/tests-visual-job-artifacts.tar.bz2
          retention-days: 1
      - name: Upload Build Artifacts - public/
        uses: actions/upload-artifact@v2
        with:
          name: public-${{ matrix.node-version }}
          path: ${{ github.workspace }}/public/
          retention-days: 1
  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Latest)
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm ci
      - name: Create Artifact Directories
        run: |
          mkdir -p ${{ github.workspace }}/public
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: public-16.x
          path: ${{ github.workspace }}/public
      - name: Deploy PREVIEW
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if [[ -n ${NETLIFY_SITE_ID} && -n ${NETLIFY_AUTH_TOKEN} ]] ; then
            npm run deploy:preview
          fi
